title: Lil'Log
name: "Lilian's Tech Blog"
author: Guangming Liu
twitter_username: liuguangming
baseurl: "/lil-log"
description: Document my learning notes.
profile_url: "http://liugmm.github.io"
url: "http://liugmm.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..4
